# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlacklistChecker < Formula
  desc "A simple tool that helps you check if your IP or CIDR is blacklisted or not."
  homepage "https://github.com/ilijamt/blacklist-checker"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.0/blacklist-checker_darwin_arm64.tar.gz"
      sha256 "67a80446f7dd2ccdfabc8bb1def94a693d71afd07b1e9fbbf8f5a24fab2fd55e"

      def install
        bin.install "blacklist-checker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.0/blacklist-checker_darwin_x86_64.tar.gz"
      sha256 "dcd09fdf0c66ddb6d00766e5cdaa67ebda0b4e12befecca92d20045941008db7"

      def install
        bin.install "blacklist-checker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.0/blacklist-checker_linux_armv6.tar.gz"
      sha256 "b912f10d8bc8429b679fc74eb3dff6eb94867bdf5ff4766e005ad125b4bc7fc8"

      def install
        bin.install "blacklist-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.0/blacklist-checker_linux_arm64.tar.gz"
      sha256 "869bbf88c4cd286dc12c198a7685110b34bde6f31fc832d96420ed0c11bc7716"

      def install
        bin.install "blacklist-checker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.0/blacklist-checker_linux_x86_64.tar.gz"
      sha256 "6d245ce48b564eb185c63134956f5cd726c93380040639e24522c782ee6d8aa1"

      def install
        bin.install "blacklist-checker"
      end
    end
  end

  test do
    system "#{bin}/blacklist-checker version"
  end
end
