# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlacklistChecker < Formula
  desc "A simple tool that helps you check if your IP or CIDR is blacklisted or not."
  homepage "https://github.com/ilijamt/blacklist-checker"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.1/blacklist-checker_darwin_x86_64.tar.gz"
      sha256 "496228ea86a7a4b5379075a77dd70ca5853df2f7d9b4738957f285ad303c3d84"

      def install
        bin.install "blacklist-checker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.1/blacklist-checker_darwin_arm64.tar.gz"
      sha256 "862d3d68f9f08c7822e41fe35247c2a6982ac9d825703b93f436293e2ad32ea2"

      def install
        bin.install "blacklist-checker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.1/blacklist-checker_linux_arm64.tar.gz"
      sha256 "af52f2cbad02e08cbce49fa024e593bec46653f41003d59dec96d7d4ec48dfae"

      def install
        bin.install "blacklist-checker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.1/blacklist-checker_linux_x86_64.tar.gz"
      sha256 "7ebdc578da683e62694b1bf9c4daffe29aa5278c57622ca772173988f570cfb6"

      def install
        bin.install "blacklist-checker"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/blacklist-checker/releases/download/v0.2.1/blacklist-checker_linux_armv6.tar.gz"
      sha256 "56477b3cbae650d3811483892640110b9d7df8ccf6a9d96e423f537b226fba6a"

      def install
        bin.install "blacklist-checker"
      end
    end
  end

  test do
    system "#{bin}/blacklist-checker version"
  end
end
