# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netprivate < Formula
  desc "A small library to test if an IP address is in the private or public range for both IPv4 and IPv6."
  homepage "https://github.com/ilijamt/blacklist-checker"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/netprivate/releases/download/v0.2.0/netprivate_darwin_x86_64.tar.gz"
      sha256 "dd27ff5624bae7d5b7f8b8362f5a47ec936fb777f63f3550f2bdf4a3ffa4d5d7"

      def install
        bin.install "is-private"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ilijamt/netprivate/releases/download/v0.2.0/netprivate_darwin_arm64.tar.gz"
      sha256 "2a9f468abacc5d4a7710e185bee1a6ba9f8646c60c292029fd0437a373e277ce"

      def install
        bin.install "is-private"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/netprivate/releases/download/v0.2.0/netprivate_linux_armv6.tar.gz"
      sha256 "e16a97168e553c1547ec1cc2f98131835cdc550594764b66d85f55f3085fccee"

      def install
        bin.install "is-private"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/netprivate/releases/download/v0.2.0/netprivate_linux_arm64.tar.gz"
      sha256 "106b0de03b3ecba04eed87ef5f2b70eb5b20105cc2ae7ebb0c4e5f6677176fc6"

      def install
        bin.install "is-private"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/netprivate/releases/download/v0.2.0/netprivate_linux_x86_64.tar.gz"
      sha256 "fd426fc5f31d69ecee44d9483411a99a2ac785086b6abfc68e2a17470e141717"

      def install
        bin.install "is-private"
      end
    end
  end

  test do
    system "#{bin}/blacklist-checker version"
  end
end
