# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTokenHelper < Formula
  desc "A token helper is an external program that Vault calls to save, retrieve or erase a saved token."
  homepage "https://github.com/ilijamt/vault-token-helper"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/v0.1.2/vault-token-helper_darwin_x86_64.tar.gz"
      sha256 "9c6b4beedf853a87843da3de62f06527cc832b404b4c5c2ff12c7f9497ceedf9"

      def install
        bin.install "vault-token-helper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/v0.1.2/vault-token-helper_darwin_arm64.tar.gz"
      sha256 "f5edddb52754ed93d619fd2894b33bcd945e02c5247054d16531e5f60399b5ca"

      def install
        bin.install "vault-token-helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/v0.1.2/vault-token-helper_linux_x86_64.tar.gz"
      sha256 "99a7911f3bac3d38e7db2ab8e625448c1672c043c8411d4a48e4de34f2401896"

      def install
        bin.install "vault-token-helper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/v0.1.2/vault-token-helper_linux_arm64.tar.gz"
      sha256 "68a010e549796c6756d1dd90ff345875f907c4739154ea41c697f40fcc4ff6ec"

      def install
        bin.install "vault-token-helper"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/v0.1.2/vault-token-helper_linux_armv6.tar.gz"
      sha256 "c37ac37b9d3bc03770d31c62631d8aa5fd2413c2ca914a3cdc83db547f70eac5"

      def install
        bin.install "vault-token-helper"
      end
    end
  end

  test do
    system "#{bin}/vault-token-helper version"
  end
end
