# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTokenHelper < Formula
  desc "A token helper is an external program that Vault calls to save, retrieve or erase a saved token."
  homepage "https://github.com/ilijamt/vault-token-helper"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/0.1.0/vault-token-helper_darwin_arm64.tar.gz"
      sha256 "2de278ea603560b83df82e3945fa1ff93364491736a245e11e3cebc6b6c721ca"

      def install
        bin.install "vault-token-helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/0.1.0/vault-token-helper_darwin_x86_64.tar.gz"
      sha256 "466353533aee1ab8c56d8f7f86a3fe8f31afa0678abc00924d50cf1b93d0f6d0"

      def install
        bin.install "vault-token-helper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/0.1.0/vault-token-helper_linux_arm64.tar.gz"
      sha256 "ec8c1f9ccf75c6ab3eddb289a0a5e92e012a1336e2e7fabe1dd9c7edfa7e546f"

      def install
        bin.install "vault-token-helper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/0.1.0/vault-token-helper_linux_x86_64.tar.gz"
      sha256 "6ef26f1ed42cd392ab5127ad3b62fc36a1683e47e3c82b37eaa105bc55fdc673"

      def install
        bin.install "vault-token-helper"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/vault-token-helper/releases/download/0.1.0/vault-token-helper_linux_armv6.tar.gz"
      sha256 "5521aaf49605efaceb5d3910cda9da29ea2570213216b7e03c95686b3a270a69"

      def install
        bin.install "vault-token-helper"
      end
    end
  end

  test do
    system "#{bin}/vault-token-helper version"
  end
end
