# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vht < Formula
  desc "A simple vault helper tool that simplifies the usage of Vault"
  homepage "https://github.com/ilijamt/vht"
  version "0.5.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.3/vht_0.5.3_darwin_arm64.tar.gz"
      sha256 "98c929677b48cbcd32374cd42ad63696efcf29dcb1d16390ddc3d2c1894d77ef"

      def install
        bin.install "vht"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.3/vht_0.5.3_darwin_amd64.tar.gz"
      sha256 "712b5e8594289f0d53deec8859e9acbfbcaae96e3ad937978adb51be9ff618c4"

      def install
        bin.install "vht"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.3/vht_0.5.3_linux_armv6.tar.gz"
      sha256 "fea4f3174a2edb2aaecb0277a2e9333b861c8775f0c73ec24bacb865a3969a5e"

      def install
        bin.install "vht"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.3/vht_0.5.3_linux_arm64.tar.gz"
      sha256 "9e6123f24d1b95c26757c920c5a4ed5fb7d3ade95d8b3fa42eebcce8e56bf6ae"

      def install
        bin.install "vht"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.3/vht_0.5.3_linux_amd64.tar.gz"
      sha256 "12f21f4b9ddcb347b42d4afc9654a1e842a4c469bc5e99ffa3c555f9711594ad"

      def install
        bin.install "vht"
      end
    end
  end

  test do
    system "#{bin}/vht version"
  end
end
