# This file was generated by GoReleaser. DO NOT EDIT.
class Vht < Formula
  desc "A simple vault helper tool that simplifies the usage of Vault"
  homepage "https://github.com/ilijamt/vht"
  version "0.3.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ilijamt/vht/releases/download/v0.3.2/vht_darwin_x86_64.tar.gz"
    sha256 "fe72d848271dd66ecb6b9b66840409cf0b59f70434f088e0eb838ed28c1f5906"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vht/releases/download/v0.3.2/vht_linux_x86_64.tar.gz"
      sha256 "34d245a426777a8515a1a10e14060cd0e45e25dd56e04deea8cb4f7643243abb"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ilijamt/vht/releases/download/v0.3.2/vht_linux_arm64.tar.gz"
        sha256 "bb871f40258291812cb307f578b27f200f86b99cabfabf10b1315a221242d9d8"
      else
        url "https://github.com/ilijamt/vht/releases/download/v0.3.2/vht_linux_armv6.tar.gz"
        sha256 "cc6ad73008c5fe9c363c4aac5eb1ee8e6d53f43962b1d4778f895064a8dbee9b"
      end
    end
  end

  def install
    bin.install "vht"
  end

  test do
    system "#{bin}/vht version"
  end
end
