# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vht < Formula
  desc "A simple vault helper tool that simplifies the usage of Vault"
  homepage "https://github.com/ilijamt/vht"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.0/vht_darwin_arm64.tar.gz"
      sha256 "e11fb53b01a229c9d340a3701f1559e7438ba19629a7ea65d2621c93d67bee88"

      def install
        bin.install "vht"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.0/vht_darwin_x86_64.tar.gz"
      sha256 "9589373afe03a4ddab9b5b1523dc575db2a3e9d8a3714c101c0cb571022c7411"

      def install
        bin.install "vht"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.0/vht_linux_armv6.tar.gz"
      sha256 "0f219d346fed2c05c12445d9d94b817d7f9c5ecc937e543ce64f782047818a4f"

      def install
        bin.install "vht"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.0/vht_linux_x86_64.tar.gz"
      sha256 "087093a7101de4264acee28b5621090a87ec12d4a0692090806a7b90a9481a70"

      def install
        bin.install "vht"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilijamt/vht/releases/download/v0.5.0/vht_linux_arm64.tar.gz"
      sha256 "db9bc0471a5e908f4e0f87c23d716d01acfae69bfca0c3446502928d7065b6a7"

      def install
        bin.install "vht"
      end
    end
  end

  test do
    system "#{bin}/vht version"
  end
end
